import { cn } from '@/lib/utils'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar'


const inter = Inter({ subsets: ['latin'] })


export const metadata: Metadata = {
  title: 'portfolio-new',
  description: 'generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn(
        'min-h-screen antialiased grainy',
        inter.className
      )}>
        <div className='font-crimson'>
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  )
}
